version: '3'
services:
  guacamole-server:
    image: guacamole/guacd:latest
    restart: unless-stopped
    networks:
      - guacamole
  guacamole-client:
    image: registry.gitlab.com/govtech-iacwg/guacamole-auth-anyhow/guacamole-client:latest
    restart: unless-stopped
    networks:
      - guacamole
    ports:
      - 8080:8080
    environment:
      - GUACD_HOSTNAME=guacamole-server
      - GUACD_PORT=4822
      - OPENID_AUTHORIZATION_ENDPOINT=${OPENID_AUTHORIZATION_ENDPOINT}
      - OPENID_JWKS_ENDPOINT=${OPENID_JWKS_ENDPOINT}
      - OPENID_ISSUER=${OPENID_ISSUER}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_REDIRECT_URI=${OPENID_REDIRECT_URI}
      - ANYHOW_AWS_LAMBDA_FUNCTION=guacamole-config
      - AWS_REGION=${ANYHOW_AWS_REGION}
      - LOGBACK_LEVEL=debug

networks:
  guacamole:
